title: "Keebs"
description: "A showcase of different keebs I've designed and used"
baseurl: "/keebs"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
permalink: "/:title"
plugins:
  - jekyll-seo-tag
  - jekyll-feed

markdown: kramdown
encoding: UTF-8
timezone: Europe/Oslo
exclude: [LICENSE, README.md, Gemfile, Gemfile.lock]
